# Generated by Django 5.1.1 on 2024-09-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_wholesalerprofile_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deal_of_the_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="wholesalerprofile",
            name="is_spotlight",
            field=models.BooleanField(default=False),
        ),
    ]
