# Generated by Django 5.1.1 on 2024-09-29 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_category_is_featured_product_is_deal_of_the_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="api.productimage"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="api.product",
            ),
        ),
    ]
