# Generated by Django 5.1.1 on 2024-10-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_order_address_order_city_order_email_order_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
