# Generated by Django 5.1.1 on 2024-10-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_order_order_status_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
