# Generated by Django 5.1.1 on 2024-10-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_order_razorpay_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.CharField(
                editable=False, max_length=20, primary_key=True, serialize=False
            ),
        ),
    ]
