# Generated by Django 5.1.1 on 2024-10-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_retailerprofile_license_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wholesalerprofile",
            name="payment_email",
        ),
        migrations.AddField(
            model_name="wholesalerprofile",
            name="contact_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
